[package]
name = "icarus"
version = "0.1.0"
authors = ["Jai A <jaiagr+gpg@pm.me>", "tk2217 <git@tk2217.com>"]
edition = "2018"
license = "MIT"
description = "Utilities for querying and parsing Minecraft metadata"
repository = "https://github.com/tk2217/icarus/"
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]
keywords = ["minecraft", "launcher"]
categories = ["game-development", "api-bindings"]
readme = "README.md"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
bytes = "1"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
sha1 = { version = "0.6.0", features = ["std"]}
